### PR TITLE
security: Add Salted Hashing 

### PR DESCRIPTION
**Pull request by sorokh**
Modified codebase to store passwords as salted hashes  in the DB.
Per password a salt is generated to create a hash. The string stored in the DB contains the salt/hash combo. 
For testing purposes same salt/hash combo is used in the test data, however when creating new parties, this will not be the case.
In case of a person password is automatically hashed when creating or updating.

### CODE REVIEW

**Comment by dimitrydhondt** [comment]
I added you to the list of collaborators. You should be able to commit to the repo now. Working with pull requests in the same team seams a bit excessive to me. Great stuff for larger scale distributed development, though. I suppose you know best the details of the merge you want to perform ? :-)

**Comment by sorokh** [comment]
thx,

will do the necessary stuff ;-)

cheers


[image: action2015 logo] <http://www.action2015.be/>[image: logo-111111]
<http://www.11.be/>


2015-12-18 18:09 GMT+01:00 dimitrydhondt <notifications@github.com>:

**Comment by sorokh** [comment]
merged

**Comment by dimitrydhondt** [comment]
Hej Wim, don't forget to run `npm run lint` before commiting :)

**Comment by dimitrydhondt** [comment]
Fixed the last linting issues.

**Pull request closed without merging**
